spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  task:
    scheduling:
      pool:
        size: 20
      thread-name-prefix: task-scheduling
mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    call-setters-on-nulls: true
