spring:
  datasource:
    url: jdbc:mysql://localhost:3306/opendoc?serverTimezone=UTC&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true&allowMultiQueries=true&useAffectedRows=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    enabled: true
    host: localhost
    port: 6379
    password:
    database: 1
  kafka:
    bootstrap-servers:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  task:
    scheduling:
      pool:
        size: 20
      thread-name-prefix: task-scheduling
mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    call-setters-on-nulls: true



cookieDomain: shellbook.com.cn
officialEmail: xagent@126.com, test@126.com